---
title: "Wk2_Lecture_Notes"
author: "Scott Smith"
date: "Tuesday, January 13, 2015"
output: html_document
---

###Correlated predictors
```{r}
library(caret); library(kernlab); data(spam)
inTrain <- createDataPartition(y = spam$type,
                               p = 0.75,
                               list = FALSE)
training <- spam[inTrain,]
testing <- spam[-inTrain,]

M <- abs(cor(training[,-58]))
diag(M) <- 0
print(which(M > 0.9, arr.ind = T))
plot(spam[,34],spam[,32])

#principal components in R - prcomp
smallSpam <- spam[,c(34,32)]
prComp <- prcomp(smallSpam)
plot(prComp$x[,1],prComp$x[,2])
prComp$rotation #principal comps rotation matrix
```


```{r}
typeColor <- ((spam$type=="spam")*1+1)
prComp <- prcomp(log10(spam[,-58]+1))
plot(prComp$x[,1],prComp$x[,2],col=typeColor,xlab="PC1",ylab="PC2")
```


## PCA with Caret
```{r}
preProc <- preProcess(log10(spam[,-58]+1),method="pca",pcaComp=2)
spamPC <- predict(preProc,log10(spam[,-58]+1))
plot(spamPC[,1],spamPC[,2],col=typeColor)
trainPC <- predict(preProc,log10(training[,-58]+1))
modelFit <- train(training$type ~ .,metod="glm",data=trainPC)
testPC <- predict(preProc,log10(testing[,-58]+1))
confusionMatrix(testing$type,predict(modelFit,testPC))

#Alternative in-line approach
modelFit <- train(training$type ~ .,
                  method = "glm",
                  preProcess = "pca",
                  data = training)

```

##Prediction through Regression
```{r}
library(caret); data(faithful); set.seed(333)
inTrain <- createDataPartition(y = faithful$waiting,
                               p = 0.5, list=FALSE)
trainFaith <- faithful[inTrain,]
testFaith <- faithful[-inTrain,]
plot(trainFaith$waiting,trainFaith$eruptions)
lm1 <- lm(eruptions ~ waiting,
          data = trainFaith)
summary(lm1)
plot(trainFaith$waiting,trainFaith$eruptions,pch=19,col="blue",xlab="Waiting",ylab="Duration")
lines(trainFaith$waiting,lm1$fitted,lwd=3)

# Predict a new value
coef(lm1)[1] + coef(lm1)[2]*80
# Or another way
newdata <- data.frame(waiting=80)
predict(lm1,newdata)
# Get training/testing set errors
# Calculate RMSE on training
sqrt(sum((lm1$fitted-trainFaith$eruptions)^2))
# Calculate RMSE on testing

## Prediction intervals
pred1 <- predict(lm1,newdata=testFaith,interval="prediction")
ord <- order(testFaith$waiting)
plot(testFaith$waiting,testFaith$eruptions,pch=19,col="blue")
matlines(testFaith$waiting[ord],pred1[ord,],type="l",,col=c(1,2,2),lty=c(1,1,1),lwd=3)
## or in caret
modFit <- train(eruptions ~ waiting,
                data = trainFaith,
                method = "lm")
summary(modFit$finalModel)
sqrt(sum((predict(lm1,newdata=testFaith)-testFaith$eruptions)^2))
```
